name: Deploy to Cloudflare Workers

on:
  push:
    branches: [ main, siteupdates ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: |
          echo "Building project..."
          npm run build
          echo "Build completed successfully"

      - name: Verify build output
        run: |
          echo "Checking build output..."
          ls -la dist/
          ls -la dist/client/ || echo "No client directory found"

      - name: Check wrangler configuration
        run: |
          echo "Wrangler configuration:"
          cat wrangler.json

      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy --compatibility-date=2025-04-01
        env:
          NODE_ENV: production
